# ========= DATABASE CONFIGURATION =========

#db url connection
db.url= jdbc:mysql://localhost:3306/hostpiatldb

#db username
db.usrname='root'
#db password
db.pssrd='Sd009036'

# ========= CONNECTION POOL SETTINGS =========
#minimum db connection(defined in some cases)
#db.pool.min_size=5

#maximum db connection
#db.pool.max_size=20

#connection timeout in seconds
#db.pool.timeout = 1800

# ========= HIBERNATE SETTINGS =========

# Sql dialect: tells hibernate which database we are using
hibernate.dialect = org.hibernate.dialect.MySQL8Dialect

# Show SQL in console (helpful for debugging)
# true = see actual SQL queries
# false = don't show SQL
hibernate.show_sql=false

# Format SQL nicely (with line breaks)
hibernate.format_sql=true

# Automatically create/update database schema
# Options:
#   create = drop existing table, create new (CAREFUL!)
#   create-drop = create on startup, drop on shutdown
#   update = add new columns/tables but keep existing data (SAFE)
#   validate = check schema matches entities (no changes)
#   none = don't touch schema
hibernate.hbm2ddl.auto=update

# ===== JDBC SETTINGS =====
# JDBC = Java Database Connectivity (low-level database access)

jdbc.driver=com.mysql.cj.jdbc.Driver

